manifest:
  remotes:
    - name: klesh
      url-base: https://github.com/klesh
  projects:
    - name: zmk
      remote: klesh
      revision: main
      import:
        file: app/west.yml
        name-blocklist:
          - zmk-ydxc02-driver
  self:
    path: config
